jenkins:
  systemMessage: "MSINIT Jenkins initialized via JCasC"

  nodes:
    - permanent:
        name: "Linux agent"
        remoteFS: "/var/jenkins"
        numExecutors: 2
        labelString: "linux-agent"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-creds"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_TOKEN}"
              description: "GitHub PAT"
          - file:
              id: "vault-env"
              fileName: "vaultservice.env"
              secretBytes: "${VAULT_ENV_FILE_BASE64}"
              description: "Env file for bootstrapping vaultservice"
          - string:
              id: "VAULT_URL"
              secret: "${VAULT_URL}"
              description: "Base URL for vaultservice"
          - string:
              id: "CICD_TOKEN"
              secret: "${CICD_TOKEN}"
              description: "Vaultservice CICD token"

jobs:
  - script: >
      if (System.getenv('AUTHSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('authservice') {
          displayName('authservice')
          branchSources {
              github {
                  id('authservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('authservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('EMAILSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('emailservice') {
          displayName('emailservice')
          branchSources {
              github {
                  id('emailservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('emailservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('FILESERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('fileservice') {
          displayName('fileservice')
          branchSources {
              github {
                  id('fileservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('fileservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('GATEWAYSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('gatewayservice') {
          displayName('gatewayservice')
          branchSources {
              github {
                  id('gatewayservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('gatewayservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('LOGGERSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('loggerservice') {
          displayName('loggerservice')
          branchSources {
              github {
                  id('loggerservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('loggerservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('REACTSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('reactservice') {
          displayName('reactservice')
          branchSources {
              github {
                  id('reactservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('reactservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('TELEMETRYSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('telemetryservice') {
          displayName('telemetryservice')
          branchSources {
              github {
                  id('telemetryservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('telemetryservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('TESTSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('testservice') {
          displayName('testservice')
          branchSources {
              github {
                  id('testservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('testservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
  - script: >
      if (System.getenv('VAULTSERVICE_INTEGRATION') == 'true') {
        multibranchPipelineJob('vaultservice') {
          displayName('vaultservice')
          branchSources {
              github {
                  id('vaultservice-github-source')
                  repoOwner('StrangeQuark')
                  repository('vaultservice')
                  includes('main')
                  scanCredentialsId('github-creds')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(2)
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
        }
      }
