services:
  jenkins-service:
    build: .
    networks:
      - jenkins-network
      - shared-network
    container_name: jenkins-service
    labels:
      com.msinit.log: "true"
      com.msinit.service-name: "jenkinsservice"
    ports:
      - "6100:8080"
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - VAULT_ENV_FILE_BASE64=${VAULT_ENV_FILE_BASE64}
      - VAULT_URL=${VAULT_URL}
      - CICD_TOKEN=${CICD_TOKEN}
    restart: unless-stopped
volumes:
  jenkins_home:
networks:
  shared-network:
    external: true
  jenkins-network:
    external: true
